### PR TITLE
Implement email signup on pledge page

### LINKED ISSUE #28: Enable people to sign up with email on pledge pages
Pledge pages should become recruitment pages for our core supporters/volunteers to be able to spread the word and get their friends to sign up and become supporters of Mayday as well.

We should be able to create leaderboards and contests, and keep track of who signed how many people up.

A

### PR DESCRIPTION
**Pull request by davidxia**
fixes #28

### CODE REVIEW

**Comment by davidxia** [comment]
cc @aaronlifshin @jwhite66 , @jtolds, @brad

I tried submitting the form and saw these logs from pledgeservice.

```
>> INFO     2014-09-20 22:40:02,827 handlers.py:322] body: email=foo%40bar.com&zipcode=10002
>> INFO     2014-09-20 22:40:02,828 env.py:126] Subscribing {'pledgePageSlug': '', 'ip_addr': '127.0.0.1', 'amount_cents': None, 'rootstrikers': '', 'otherVars': {}, 'email': u'foo@bar.com', 'last_name': None, 'source': 'subscribe', 'zipcode': u'10002', 'skills': None, 'volunteer': '', 'first_name': None, 'phone': None, 'time': datetime.datetime(2014, 9, 20, 22, 40, 2, 828924)}
>> INFO     2014-09-20 22:40:02,836 module.py:652] default: "POST /r/subscribe HTTP/1.1" 302 -
>> INFO     2014-09-20 22:40:02,846 module.py:652] default: "GET /pledge?email=foo@bar.com HTTP/1.1" 200 6950
```

This request flowed through [this line of code in pledgeservice.git](https://github.com/MayOneUS/pledgeservice/blob/1e5b7d6f7e5a59837140408e8f0bf2663cb5ccd2/backend/env.py#L126). So I assume it should work in production.

There's no email validation right now. I can submit "foo@bar" as an email and it seems to subscribe to mailchimp. It seems like the right place to validate emails is [here](https://github.com/MayOneUS/pledgeservice/blob/1e5b7d6f7e5a59837140408e8f0bf2663cb5ccd2/backend/handlers.py#L326)?

**Comment by aaronlifshin** [comment]
Thanks, @davidxia

I will do the final testing on this.  Access to MailChimp is helpful here, and as that is our main asset, very few people have it.  I didn't see foo@bar address make it in there, or in the error logs (which is where I would expect it to end up after mailchimp rejects it)

I think there was another issue about handling mailchimp rejections better.

**Comment by aaronlifshin** [comment]
I also have an issue out with Mario, who is developing the homepage to add better validation at that level.  I think validating as much as possible in the browser is a good approach here.

**Comment by aaronlifshin** [comment]
Tested email in my local machine, it added fine to Mailchimp, but did not increment the Team count.

**Comment by davidxia** [comment]
@aaronlifshin I was using the testing config which just logs the mailchimp subscription but doesn't call the real API I think. That's probably why "foo@bar" doesn't appear anywhere.

Yea, I didn't do the incrementing of the team count yet.

**Comment by aaronlifshin** [comment]
Still an improvement over current even without that. My plan is to merge
Steve's home page changes in and do a deploy tomorrow at the latest.

A

**Comment by aaronlifshin** [comment]
It's live.  Now let's get the counting in there.

A

**Comment by davidxia** [comment]
Oh nice! I'll work on this tonight.

On Mon, Sep 22, 2014 at 3:57 PM, Aaron Lifshin notifications@github.com
wrote:

> It's live. Now let's get the counting in there.
> 
> A
> 
> On Sun, Sep 21, 2014 at 12:48 PM, Aaron Lifshin aaronlifshin@gmail.com
> wrote:
> 
> > Still an improvement over current even without that. My plan is to merge
> > Steve's home page changes in and do a deploy tomorrow at the latest.
> > 
> > A
> > On Sep 21, 2014 9:42 AM, "David Xia" notifications@github.com wrote:
> > 
> > > @aaronlifshin https://github.com/aaronlifshin I was using the
> > > testing
> > > config which just logs the mailchimp subscription but doesn't call the
> > > real
> > > API I think. That's probably why "foo@bar" doesn't appear anywhere.
> > > 
> > > Yea, I didn't do the incrementing of the team count yet.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/MayOneUS/teams/pull/32#issuecomment-56304469.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MayOneUS/teams/pull/32#issuecomment-56431612.

## 

David Xia
davidxia.com

**Comment by davidxia** [comment]
@aaronlifshin It seems that to increment the count in Team model, I can't just have the teams app send a request to an endpoint handled by the pledgeservice since pledgeservice doesn't have code for the Team model. I'll have to POST to an endpoint handled by teams which sends a request to pledgeservice, gets an OK status, and then increments the count.

Does this sound right? Just making sure I'm not doing something unecessary.

**Comment by davidxia** [comment]
WIP here https://github.com/davidxia/teams/tree/increment-team-joined-count

**Comment by aaronlifshin** [comment]
Sorry for the slow response on this one.  It is broadly correct, you need
to get a request into teams and into pledgeservice.

**Pull request merged**
