### PR TITLE
Zocial login buttons

### PR DESCRIPTION
**Pull request by erinzm**
Title self-explanatory. Very pretty.
Can anyone check my changes? Docker's broken on my computer right now, so I can't test the buttons yet.

### CODE REVIEW

**Comment by aaronlifshin** [comment]
Oops, Liam, my other note should have been to this ticket.

**Comment by erinzm** [comment]
Sure, I'll take a look. Zocial actually _wasn't_ my first choice for the buttons.

**Comment by erinzm** [comment]
Yeah, I've used Font Awesome before.
BTW, the login buttons on the redesign repo would look better if the icons were _in_ the buttons.
Take a look at this, it's built on FontAwesome + Bootstrap: https://gae-init.appspot.com/signin/
We can stick those little buttons under a **Login** header in the login modal.

**Comment by aaronlifshin** [comment]
Agreed, let's try those.

If you can wrangle this login stuff into the common style repo, more power
to you.

A

**Comment by erinzm** [comment]
Opening new issue for login buttons: [MayOneUS/homepage_redesign#2](https://github.com/MayOneUS/homepage_redesign/issues/2).

**Pull request merged**
