### PR TITLE
embed pledge form on the team page

### PR DESCRIPTION
**Pull request by brad**
As requested by @aaronlifshin 
Here is a functional first draft. The pledge button on the left of the page continues to take the user to `https://pledge.mayday.us/pledge?team=<team_key>` but the pledge button on the right will open the Stripe form and then send you to the receipt page on successful payment.
mayday us - my superpac 2014-06-08 13-41-38

### CODE REVIEW

**Comment by erinzm** [comment]
That's _just slightly_ odd to have two pledge buttons ;)

**Comment by brad** [comment]
I think I agree, but I am not a UX expert. Aaron just told me he wanted an embedded pledge form in the sidebar so that's what I did, and left everything else the same. Do you have any ideas about how to fix the oddness?

**Comment by jtolio** [comment]
hmm, would it be possible to do this as an iframe hosted by pledge.mayone.us @brad ?

**Comment by jtolio** [comment]
i mean, this looks good, so if you want to submit, cool, but it would be fantastic to keep all the pledge form logic in the same repo

**Comment by brad** [comment]
@jtolds It's possible, I guess the only issue is that when we redirect to the receipt page, that would all be within the iframe. We could make an embedded version of the receipt page for that if that is a desired thing.
Also, technically speaking all the actual logic is still in the pledge repo since I load the JavaScript from there. Although one could make the argument that the angular attributes are a form of logic.

**Comment by jtolio** [comment]
up to you. the embed pledge form if it was an iframe could easily have a target for the pledge button to open an new tab or window. it might even be nice to have the receipt in the iframe frankly

but yeah, up to you what you want to do

**Comment by aaronlifshin** [comment]
The issue will be if we change some of that copy on checkboxes or field
names, we will have to change it in two places.

For now I am going to move this out into another URL and test it.

A

**Comment by aaronlifshin** [comment]
Ok, so this new form can now be accessed with /t2/<slug>

The progress bar is not working in this page.  @brad, can you please have a look?  (I hope I didn't mess this up in the porting over to a separate page)

**Comment by aaronlifshin** [comment]
Never mind, @brad.  Fixed.

**Pull request merged**
